# config/config.yaml
# This file contains the configuration settings for the application.


gcs:
  bucket: us-campaign-finance-fec-2019-2020
  upload_folder : bronze-layer
  credentials_file: credentials/gcs_credentials.json


mysql:
  host: host_name
  database: db_name
  port: 3306
  username: username
  password: password

fec_data_files:
  - file : "data/ccl.txt"
    table_name : "candidate_committee_linkage"
    columns :
      - "CAND_ID"
      - "CAND_ELECTION_YR"
      - "FEC_ELECTION_YR"
      - "CMTE_ID"
      - "CMTE_TP"
      - "CMTE_DSGN"
      - "LINKAGE_ID" 
  - file : "data/cn.txt"
    table_name : "candidate_master"
    columns :
      - "CAND_ID"
      - "CAND_NAME"
      - "CAND_PTY_AFFILIATION"
      - "CAND_ELECTION_YR"
      - "CAND_OFFICE_ST"
      - "CAND_OFFICE"
      - "CAND_OFFICE_DISTRICT"
      - "CAND_ICI"
      - "CAND_STATUS"
      - "CAND_PCC"
      - "CAND_ST1"
      - "CAND_ST2"
      - "CAND_CITY"
      - "CAND_ST"
      - "CAND_ZIP"
  - file : "data/cm.txt"
    gcs_folder : "committee-master"
  - file : "data/webl20.txt"
    gcs_folder : "house-senate-current-campaign"
  - file : "data/weball20.txt"
    gcs_folder : "all-candidates"
  - file : "data/webk20.txt"
    gcs_folder : "pac-summary"
  - file : "data/indiv20/by_date"
    gcs_folder : "individual-contributions-by-date"
  - file : "data/itpas2.txt"
    gcs_folder : "contributions-from-candidates-to-candiates-and-independent-expenditures"
  - file : "data/itoth.txt"
    gcs_folder : "any-transcations-from-one-committee-to-another"
  - file : "data/oppexp.txt"
    gcs_folder : "operating-expenditures"
